title: "Pod 22.AUG.PREP.1 (Jekyll Jackals)"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
